### ISSUE TITLE
If all scenarios pass on retry, protractor still exits with status code 1

### ISSUE THREAD

**Issue by achuinard** [protractor-cucumber-framework/protractor-cucumber-framework#176]
I am trying to debug an issue where I am using the new CucumberJS retry option yet the protractor process still returns an exit code of 1. My guess is that protractor-cucumber-framework reports the results to protractor which protractor then checks the `failedCount` and exists appropriately.

I don't know the best spot to fix this - in protractor? In protractor-cucumber-framework?

One idea I had was that `protractor-cucumber-framework` would not report a failure to protractor if the retry worked, only if strict mode was false. Is this a valid option?

Right now, this is killing my ability to include this in my pipelines, as they evaluate the exit code. I would like my build to pass if everything works on retry.

**Comment by sromeu-ob** [comment]
I have the same issue

**Comment by achuinard** [comment]
@AlexandrosD @darrinholst any ideas where this needs to get fixed?

**Comment by achuinard** [comment]
@sromeu-ob Did you ever find a solution? Surprised no one else has chimed in here.

**Comment by achuinard** [comment]
Got a solution here - https://github.com/protractor-cucumber-framework/protractor-cucumber-framework/pull/178 - works well for my using C6.

**Comment by okkes** [comment]
> Got a solution here - #178 - works well for me using C6.

I have tested your solution and it seems to be working 👍 Hopefully it will be added to the master branch anytime soon.

**Comment by achuinard** [comment]
Haven't heard anything from the repo owners, yet.

**Comment by pawelus** [comment]
@achuinard how will your solution behave when `restartBrowserBetweenTests` is `true` in Protractor config? As far as I can see you're not sending test fail/pass to Protractor so the retry will not have clean browser state in such case if I'm not mistaken.

**Comment by achuinard** [comment]
> @achuinard how will your solution behave when `restartBrowserBetweenTests` is `true` in Protractor config? As far as I can see you're not sending test fail/pass to Protractor so the retry will not have clean browser state in such case if I'm not mistaken.

Not sure, that option supposedly made tests run really slow so I don't bother with it. Give it a try yourself and report back?

**Comment by Phonesis** [comment]
Wondered if any update on this fix making it to master? Seeing this bug cause major issues with our pipelines atm :(

**Comment by achuinard** [comment]
It just was merged, @AlexandrosD do we need a version bump / release?

**Comment by Phonesis** [comment]
When can we download this? Guess it needs a version bump?

**Comment by pawelus** [comment]
@achuinard I checked Protractor code and your solution will not work properly with `restartBrowserBetweenTests` as Protractor only restarts the browser on test pass/fail event

**Comment by Phonesis** [comment]
> @achuinard I checked Protractor code and your solution will not work properly with `restartBrowserBetweenTests` as Protractor only restarts the browser on test pass/fail event

Just as an aside, I have never been able to get restartBrowserBetweenTests to work myself. It never seems to re launch a new session. Just errors that the webdriver has been closed.

**Comment by pawelus** [comment]
> Just as an aside, I have never been able to get restartBrowserBetweenTests to work myself. It never seems to re launch a new session. Just errors that the webdriver has been closed.
That usually means you're not handling promises correctly. `restartBrowserBetweenTests` works well for me with hundreds of tests.
Sure documentation says "it will make your test slow" but the only thing it does is to restart the browser (to get a clean session) after each test which adds maybe 1s per test.

I looked into Protractor code again and we might be ok here after all as `protractor-cucumber-framework` is using the `afterAll()` function and that will restart the browser after scenario finishes regardless of testPass/Fail` events (I forgot steps are treated as tests here to get proper reporting in IDEs).
@achuinard @AlexandrosD should it be mentioned somewhere that failing step won't be registered anywhere? If we don't emit anything then IDEs will not see the failing step at all but they will still see all passing steps prior to the failing one

**Comment by Phonesis** [comment]
> > Just as an aside, I have never been able to get restartBrowserBetweenTests to work myself. It never seems to re launch a new session. Just errors that the webdriver has been closed.
> 
> That usually means you're not handling promises correctly. `restartBrowserBetweenTests` works well for me with hundreds of tests.
> Sure documentation says "it will make your test slow" but the only thing it does is to restart the browser (to get a clean session) after each test which adds maybe 1s per test.
> 
> I looked into Protractor code again and we might be ok here after all as `protractor-cucumber-framework` is using the `afterAll()` function and that will restart the browser after scenario finishes regardless of testPass/Fail` events (I forgot steps are treated as tests here to get proper reporting in IDEs).
> 
> @achuinard @AlexandrosD should it be mentioned somewhere that failing step won't be registered anywhere? If we don't emit anything then IDEs will not see the failing step at all but they will still see all passing steps prior to the failing one

Are you using an async await pattern though? And with cucumber.js? I think the issue is related to the use of those perhaps. Everything works great for us except restartBrowserBetweenTests. None of the browser settings are read and it complains no SessionId exists upon relaunching the browser window. The URL loads then it just hangs.

**Comment by pawelus** [comment]
> Are you using an async await pattern though? And with cucumber.js? I think the issue is related to the use of those perhaps. Everything works great for us except restartBrowserBetweenTests. None of the browser settings are read and it complains no SessionId exists upon relaunching the browser window. The URL loads then it just hangs.

@Phonesis yes I use `async/await`, `cucumber 5.1.0`, `protractor-cucumber-framework 6.1.0`. Things you describe are almost always caused by incorrect promise handling. `protractor-cucumber-framework` used to have this problem but it was fixed in `5.0.0`

**Comment by Phonesis** [comment]
> > Are you using an async await pattern though? And with cucumber.js? I think the issue is related to the use of those perhaps. Everything works great for us except restartBrowserBetweenTests. None of the browser settings are read and it complains no SessionId exists upon relaunching the browser window. The URL loads then it just hangs.
> 
> @Phonesis yes I use `async/await`, `cucumber 5.1.0`, `protractor-cucumber-framework 6.1.0`. Things you describe are almost always caused by incorrect promise handling. `protractor-cucumber-framework` used to have this problem but it was fixed in `5.0.0`

Odd I still have the issue with all those versions or higher. 

@AlexandrosD  any change of a version bump with the fix this week? Thanks in advance

**Comment by brandonparrottFR** [comment]
@AlexandrosD do you happen to have an expected ETA for a newer version that contains the fix for this issue? We just upgraded to cucumber 6.x and having a ton of problems in our pipeline.

**Comment by Phonesis** [comment]
> I am trying to debug an issue where I am using the new CucumberJS retry option yet the protractor process still returns an exit code of 1. My guess is that protractor-cucumber-framework reports the results to protractor which protractor then checks the `failedCount` and exists appropriately.
> 
> I don't know the best spot to fix this - in protractor? In protractor-cucumber-framework?
> 
> One idea I had was that `protractor-cucumber-framework` would not report a failure to protractor if the retry worked, only if strict mode was false. Is this a valid option?
> 
> Right now, this is killing my ability to include this in my pipelines, as they evaluate the exit code. I would like my build to pass if everything works on retry.

Has 6.2.1 fixed your issue?  I am still seeing same behaviour but am now wondering if it's caused by BrowserStack exe we use to run tests:

```
[16:20:38] I/launcher - 0 instance(s) of WebDriver still running
[16:20:38] I/launcher - Edge #31 passed
[16:20:38] I/launcher - Firefox #41 passed
[16:20:38] I/launcher - Chrome #61 passed
[16:20:38] I/launcher - Chrome #51 passed
[16:20:38] I/launcher - android #81 passed
[16:20:38] I/launcher - Safari #71 passed
[16:20:38] I/launcher - IE #11 passed
[16:20:38] I/launcher - iPhone #01 passed
[16:20:38] I/launcher - IE #21 failed 2 test(s)
[16:20:38] I/launcher - overall: 2 failed spec(s)t
Stopping BrowserStack Local...
[16:20:44] E/launcher - Process exited with error code 1
```

In the above output with 6.2.1 the IE instance failed twice but both scenarios retried and passed. However, the exit code was still 1.

**Comment by sahilpurav** [comment]
I'm still getting the same error even after upgrading to v6.2.1

**Comment by xiuzhen1103** [comment]
> I'm still getting the same error even after upgrading to v6.2.1

Same here, did you get the fix? anyone have a look？

**Comment by Phonesis** [comment]
I was never able to get it to work and ended up writing a script to handle the situation. It is annoying having to do it as adds a lot of overhead but works. It creates a txt file with a test/fail result logged for each test. At end of the run it will check if any txt file includes a fail status. If not, it will override exit code to ensure pipeline passes

**Comment by pillsilly** [comment]
the issue seemed to be back in latest version 7 & 8.  but the code structure seemed to be changed a lot since 6.2.1.

@AlexandrosD  would you maybe suggest for a solution?  I'm willing to provide fix if possible.

**Comment by thinkingerrol** [comment]
Workaround: when starting the `protractor`, I append the following to its command line:
```
const directory = 'build';
ensureDirSync(directory);
const cucumberSummary = join(directory, 'cucumberSummary.log');
protractorCommandLine += `--cucumberOpts.format=summary:${cucumberSummary} \
      || grep -P "^(\\d*) scenarios? \\(.*?\\1 passed" ${cucumberSummary} \
      && rm ${cucumberSummary}`;
```
